### ISSUE TITLE
Duplicate instance check broken

### ISSUE THREAD

**Issue by krayon** [maclarel/ghes-hotpatch-validator#6]
The code appears to be wanting to check for duplicates:

```bash
    # Verify that we're only running *one* unique hash per service
    # to avoid duplicate containers
    NUM_RUNNING_HASHES_FOR_SERVICE=$(echo "$RUNNING_TAG" | wc -w)
    if [ "$NUM_RUNNING_HASHES_FOR_SERVICE" -gt 1 ]
    then
      echo "ERROR: More than 1 running hash for service $s! Got: $NUM_RUNNING_HASHES_FOR_SERVICE Expected: 1."
      export FAILURE_STATUS=true
    fi
```

However, it does not, due to `RUNNING_TAG` earlier being defined as:

```bash
RUNNING_TAG=$(docker ps | grep "$s" | awk '{print $2}' | cut -d':' -f2 | sort -u)
```

The `sort -u` will ensure that only 1 result is ever returned.

**Comment by maclarel** [comment]
Kind of - what this is looking for is multiple *unique* images running for a service. We've had a few scenarios, for example, where containers will not be properly stopped and as a result we'll have something like `unicorn` running on version X and version Y simultaneously. With this in mind, the `sort -u` will properly only return multiple results if there are multiple _different_ hashes.
 
This is extremely rare, but has happened often enough that it warrants a check.
